# Generated by Django 5.2.14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_settings', '0021_dynamic_payments_product_lines'),
        ('customers', '0005_customermedia_compression'),
        ('sales_leads', '0005_interim_payment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_date', models.DateField(verbose_name='Teklif tarihi')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Geçerlilik')),
                ('project', models.CharField(blank=True, max_length=255, verbose_name='Proje referansı')),
                ('sale_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Toplam (₺)')),
                ('down_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Peşinat (₺)')),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('sent', 'Gönderildi'), ('accepted', 'Kabul'), ('rejected', 'Red'), ('converted', 'Satışa dönüştü')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Not')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('converted_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_quote', to='sales_leads.saleslead', verbose_name='Dönüşen satış')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_quotes', to='customers.customer', verbose_name='Müşteri')),
            ],
            options={
                'verbose_name': 'Teklif',
                'verbose_name_plural': 'Teklifler',
                'ordering': ['-quote_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesQuoteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Adet')),
                ('note', models.CharField(blank=True, max_length=500, null=True, verbose_name='Not')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_lines', to='core_settings.productcoloroption', verbose_name='Renk')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quote_lines', to='core_settings.productoption', verbose_name='Ürün')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales_leads.salesquote', verbose_name='Teklif')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
