# Generated by Django 5.2.14 on 2026-06-08 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_settings', '0057_plan_modules_and_panel_limits'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpayable',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_payables', to='core_settings.businessbrand', verbose_name='Marka'),
        ),
    ]
