# Generated by Django 5.2.14 on 2026-06-07 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_settings', '0057_plan_modules_and_panel_limits'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_categories', to='core_settings.businessbrand')),
            ],
            options={
                'verbose_name': 'Menü kategorisi',
                'verbose_name_plural': 'Menü kategorileri',
                'ordering': ('sort_order', 'name'),
                'unique_together': {('brand', 'name')},
            },
        ),
        migrations.CreateModel(
            name='RestaurantMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_menu_items', to='core_settings.businessbrand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='restaurant.restaurantcategory')),
            ],
            options={
                'verbose_name': 'Menü ürünü',
                'verbose_name_plural': 'Menü ürünleri',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='RestaurantTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('capacity', models.PositiveSmallIntegerField(default=4)),
                ('status', models.CharField(choices=[('empty', 'Boş'), ('occupied', 'Dolu'), ('bill_requested', 'Hesap istendi')], default='empty', max_length=20)),
                ('branch', models.ForeignKey(blank=True, help_text='Bayi/franchise şubesi; boşsa merkez masası.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_branch_tables', to='core_settings.businessbrand')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_tables', to='core_settings.businessbrand')),
            ],
            options={
                'verbose_name': 'Masa',
                'verbose_name_plural': 'Masalar',
                'unique_together': {('brand', 'branch', 'name')},
            },
        ),
    ]
