# Generated by Django 5.2.14 on 2026-06-08 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_settings', '0058_brand_tenant_scope'),
        ('tools', '0008_alter_mapsscrapedfirm_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapsscrapedfirm',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scraped_firms', to='core_settings.businessbrand', verbose_name='Marka'),
        ),
        migrations.AddField(
            model_name='outreachcollection',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outreach_collections', to='core_settings.businessbrand', verbose_name='Marka'),
        ),
        migrations.AddField(
            model_name='whatsappconnection',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_connections', to='core_settings.businessbrand', verbose_name='Marka'),
        ),
    ]
